#配置服务器端口
server:
  port: 8090
#配置nacos服务注册中心
spring:
  application:
    name: passport  #服务名字（会暴露在nacos服务注册中心）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务注册中心的服务器地址
  #配置视图解析器
  mvc:
    view:
      prefix: /pages/ #前缀
      suffix: .html #后缀
#设置负载均衡策略。
#provider-service 是要请求的微服务名称，即为当前服务提供服务的spring.application.name 属性值
provider-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule